version: '3.7'

services:
  infra:
    container_name: infra
    image: infra3
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TERRAFORM_VERSION: ${TERRAFORM_VERSION}
        GCLOUD_VERSION: ${GCLOUD_VERSION}
    volumes:
      - .:/project
    env_file: 
      - aws_credentials.env
      - gcp.env
    entrypoint: /project/entrypoint.sh