version: '3.7'

services:
  aws-infra-cli:
    container_name: aws-infra-cli
    image: aws-infra-cli
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TERRAFORM_VERSION: ${TERRAFORM_VERSION}
        GCLOUD_VERSION: ${GCLOUD_VERSION}
    volumes:
      - .:/project
    env_file: 
      - aws_credentials.env
      - gcp.env
    entrypoint: /project/entrypoint.sh